sonar.organization=accelerationconsortium
sonar.projectKey=AccelerationConsortium_opentrons-flex
sonar.projectName=opentrons-flex

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
